# Generated by Django 5.1.4 on 2026-03-09 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='phone_number',
        ),
    ]
